export const CHANGE_CATEGORY: string = "CHANGE_CATEGORY";
export const GET_CATEGORIES_SUCCESS: string = "GET_CATEGORIES_SUCCESS";

export const GET_PRODUCTS_SUCCESS: string = "GET_PRODUCTS_SUCCESS";
export const CREATE_PRODUCT_SUCCESS: string = "CREATE_PRODUCTS_SUCCESS";
export const UPDATE_PRODUCT_SUCCESS: string = "UPDATE_PRODUCTS_SUCCESS";

export const ADD_TO_CART: string = "ADD_TO_CART";
export const REMOVE_FROM_CART: string = "REMOVE_FROM_CART";
